# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :build do
    increment_build_number(xcodeproj: "gael.xcodeproj")
    build_app(scheme: "gael", xcargs: "-allowProvisioningUpdates", silent: true, suppress_xcode_output: true,)
  end

  lane :checks do
    build
    upload_to_checks
  end

  lane :beta do
    build
    upload_to_testflight
  end

end
